### ISSUE TITLE
Build your own variation of Digital Clock

### ISSUE THREAD

**Issue by codeclassifiers** [codeclassifiers/react30_3_digital_clock#1]
Modify the CSS or the base code to build your own version of digital clock.
Submissions by multiple contributors to this issue are allowed.
Steps to contribute:
1. Comment on this issue if you are interested in building your own version
2. Wait for being assigned to the issue and getting solution number
3. Once solution number is assigned, clone the repository and create a folder `solution_[your_assigned_number]` in the repo.
    For example if `solution_3` is assigned to you then you need to create a folder `solution_3` in this repo.
4. If you are a beginner who would only like to modify CSS then copy the code from `solution_1` folder into your assigned folder. If you know react and want to build your own solution then copy the code from `1_starter_code` into your assigned folder.
5. Once finished submit your solution as pull request to this repository. 

Note: No pull request will be accepted until you are added as an assignee to this issue.

**Comment by kryptondv** [comment]
I'd like to do that.

**Comment by codeclassifiers** [comment]
@kryptondv You have been added as a contributor. Feel free to fork the project and build your own solution to the problem using the starter template code in `1_starter_project` folder.
If you would like to submit a PR back then add your solution in `solution_2` folder similar to the directory structure of `solution_1` folder.
You can comment here if you have any doubts.

**Comment by codeclassifiers** [comment]
@kryptondv Your solution has been merged with main branch. Thank you for your contribution to this repository.

**Comment by AaronF3PS** [comment]
i would like to take this up

**Comment by stahura** [comment]
I'd like to be added
