### ISSUE TITLE
Update README with learning resources for useEffect hook

### ISSUE THREAD

**Issue by codeclassifiers** [codeclassifiers/react30_3_digital_clock#2]
Update the README file with learning resources related to React.js useEffect hook

**Comment by bineetNaidu** [comment]
I am Welling to contribute on to this project. Feel free to assign me to work on any issue.

**Comment by codeclassifiers** [comment]
@bineetNaidu Added you as a contributor.
The README file needs to be updated with the learning resources section.
Any Youtube tutorials or articles from Medium, Dev.to or Hashnode related to `useEffect` hook can be added in this section.

**Comment by codeclassifiers** [comment]
@bineetNaidu Thank you for your contribution.

**Comment by AaronF3PS** [comment]
I would to add in this project. This is for the hacktober fest

**Comment by JiriJAdam** [comment]
Hello, I would like to contribute to the READ.me files for educational links for all languages.
